In [3]:
import numpy as np

In [4]:
song=[[1,2,3],[4,5,6]]
matrix=np.array(list(song))

In [5]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.mean(matrix,axis=0)

array([2.5, 3.5, 4.5])

In [7]:
1 2 3
4 5 6

5 7 9

SyntaxError: invalid syntax (1664797284.py, line 1)

In [8]:
np.mean(matrix,axis=1)

array([2., 5.])

In [ ]:
1 4
2 5
3 6

6 15

In [9]:
a_dict = {
    'a':"1",
    'b':"2"
}

In [10]:
a_dict['b']
a_dict['c']

KeyError: 'c'

In [13]:
a_dict=defaultdict(lambda :"None")
a_dict['a']="1"
a_dict['b']="2"

In [14]:
print(a_dict['b'])
print(a_dict['c'])

2
None


In [12]:
from collections import defaultdict

def flatten_dict_list(dict_list):
    
    flattened_dict=defaultdict()
    print(dict_list[0])
    for key in dict_list[0].keys():
        print(key)
        flattened_dict[key]=[]
     
    for dictionary in dict_list:
        for key, value in dictionary.items():
            print(f'{key} value is {value}')
            flattened_dict[key].append(value)
            
    return flattened_dict

In [15]:
flatten_dict_list([{'name': 'Come As You Are', 'year':1991},
                {'name': 'Smells Like Teen Spirit', 'year': 1991},
                {'name': 'Lithium', 'year': 1992},
                {'name': 'All Apologies', 'year': 1993},
                {'name': 'Animals', 'year': 2014}])

{'name': 'Come As You Are', 'year': 1991}
name
year
name value is Come As You Are
year value is 1991
name value is Smells Like Teen Spirit
year value is 1991
name value is Lithium
year value is 1992
name value is All Apologies
year value is 1993
name value is Animals
year value is 2014


defaultdict(None,
            {'name': ['Come As You Are',
              'Smells Like Teen Spirit',
              'Lithium',
              'All Apologies',
              'Animals'],
             'year': [1991, 1991, 1992, 1993, 2014]})

In [16]:
l = [[1,2],[4,5]]
a = [[4,5],[1,2]]

In [17]:
from sklearn.metrics import euclidean_distances
from scipy.spatial.distance import cdist

distance=cdist(l,a,'cosine')
distance

array([[2.21975859e-02, 2.22044605e-16],
       [0.00000000e+00, 2.21975859e-02]])

In [20]:
dummy = np.arange(0,5)
dummy.shape

(5,)

In [22]:
dummy = dummy.reshape(1,-1)
dummy.shape

(1, 5)

In [23]:
dummy

array([[0, 1, 2, 3, 4]])